# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Brain Dump
email: floooh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is the blog and personal web page of Andre Weissflog (Floh,
    floooh, flohofwoe) mostly about programming stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://floooh.github.io" # the base hostname & protocol for your site
twitter_username: flohofwoe
github_username:  floooh

# Build settings
markdown: kramdown
highlighter: rouge
